// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    partial class AnimalShelterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .HasColumnType("longtext");

                    b.Property<string>("FunFact")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = 3,
                            Breed = "Cat",
                            FunFact = "Naps a lot. Loves staring at birds. Speaks English",
                            Name = "Muffin"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = 1,
                            Breed = "Cat",
                            FunFact = "Smells like Drakar Noir. Cuddly, Hairless.",
                            Name = "Stinky"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = 40,
                            Breed = "Cat",
                            FunFact = "Actually human, but pretends to be a cat. Could use a nice home, psychiatrist, and medication.",
                            Name = "Steve"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = 6,
                            Breed = "Dog",
                            FunFact = "Poops chocolate. Know how to code in C#. Allergic to water",
                            Name = "Zorthrax"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = 2,
                            Breed = "Dog",
                            FunFact = "Sings beautifully. Crows like a rooster. Is a delivery driver for Amazon",
                            Name = "The Dog Formerly Known as Prince"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = 1,
                            Breed = "Tiger",
                            FunFact = "Previous owner was terrible at animal identification. Gluten-free. Flys",
                            Name = "Lion"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
